networks:
  stations-net:
    name: stations-net
    driver: bridge
    internal: true

secrets:
  server-secret:
    environment: SERVER_SECRET
  station-secrets:
    environment: STATION_SECRETS
  
volumes:
  logs:
    name: "logs"
  data-db:
    name: "data-db"