services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    hostname: weather-station-frontend
    container_name: weather-station-frontend
    ports:
      - "8080:8080"
    environment:
      - DB_PATH
    volumes:
      - data-db:${DB_PATH}:ro